spring:
  application:
    name: paymentDeliveryService

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        orderRecieved-in-0:
          destination: order.event
          content-type: application/json
          group: ${spring.application.name}

        orderAcknowledgement-out-1:
          destination: order.event1
          content-type: application/json
          group: ${spring.application.name}

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 9096
